=== KMextensionProject/JsonSchemaGenerator/src/main/resources/sample_schemas/POST_ValidationCheck.json
{
  "$schema": "http://json-schema.org/draft-03/schema#",
  "type": "array",
  "additionalItems": false,
  "items": {
    "type": "object",
    "additionalProperties": false,
    "properties": {
      "kontrola_ziadosti_vys_id": {
        "type": [
          "integer",
          "null"
        ]
      },
      "kontrola_ziadosti_id": {
        "type": [
          "integer",
          "null"
        ]
      },
      "typ_kontroly_ziadosti_id": {
        "type": [
          "integer",
          "null"
        ]
      },
      "typ_kontroly_ziadosti_label": {
        "type": [
          "string",
          "null"
        ]
      },
      "hodnota": {
        "type": [
          "string",
          "null"
        ]
      },
      "vysledok": {
        "type": [
          "boolean",
          "null"
        ]
      },
      "zamestnavatelia": {
        "type": "array",
        "additionalItems": false,
        "items": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "identifikacne_cislo": {
              "type": [
                "string",
                "null"
              ]
            },
            "nazov": {
              "type": [
                "string",
                "null"
              ]
            },
            "stat_label": {
              "type": [
                "string",
                "null"
              ]
            },
            "Adresa": {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "ulica": {
                  "type": [
                    "string",
                    "null"
                  ]
                },
                "cislo": {
                  "type": [
                    "string",
                    "null"
                  ]
                },
                "psc": {
                  "type": [
                    "string",
                    "null"
                  ]
                },
                "obec": {
                  "type": [
                    "string",
                    "null"
                  ]
                }
              }
            },
            "Poistenci": {
              "type": "array",
              "additionalItems": false,
              "items": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                  "rodne_cislo": {
                    "type": [
                      "string",
                      "null"
                    ]
                  },
                  "meno": {
                    "type": [
                      "string",
                      "null"
                    ]
                  },
                  "priezvisko": {
                    "type": [
                      "string",
                      "null"
                    ]
                  },
                  "datum_narodenia": {
                    "type": [
                      "string",
                      "null"
                    ],
                    "format": "date-time"
                  }
                }
              }
            }
          }
        },
        "required": false
      }
    }
  }
}

=== KMextensionProject/JsonSchemaGenerator/src/main/resources/sample_schemas/POST_ValidationCheckData.json
[
  {
    "kontrola_ziadosti_vys_id": 55,
    "kontrola_ziadosti_id": 11,
    "typ_kontroly_ziadosti_id": 1,
    "hodnota": "31",
    "vysledok": true,
    "typ_kontroly_ziadosti_label": "Dĺžka obdobia registrácie zamestnanca"
  },
  {
    "kontrola_ziadosti_vys_id": 56,
    "kontrola_ziadosti_id": 11,
    "typ_kontroly_ziadosti_id": 2,
    "hodnota": "61",
    "vysledok": true,
    "typ_kontroly_ziadosti_label": "Dĺžka obdobia registrácie zamestnávateľa/SZČO"
  },
  {
    "kontrola_ziadosti_vys_id": 57,
    "kontrola_ziadosti_id": 11,
    "typ_kontroly_ziadosti_id": 3,
    "hodnota": "2.2",
    "vysledok": true,
    "typ_kontroly_ziadosti_label": "Počet percent vyslaných zamestnancov (v %) vysielajúceho zamestnávateľa"
  },
  {
    "kontrola_ziadosti_vys_id": 58,
    "kontrola_ziadosti_id": 11,
    "typ_kontroly_ziadosti_id": 4,
    "hodnota": "13",
    "vysledok": true,
    "typ_kontroly_ziadosti_label": "Súčet období počtu dní za predchádzajúcich vyslaní"
  },
  {
    "kontrola_ziadosti_vys_id": 59,
    "kontrola_ziadosti_id": 11,
    "typ_kontroly_ziadosti_id": 5,
    "hodnota": "1",
    "vysledok": true,
    "typ_kontroly_ziadosti_label": "Saldokonto odvádzateľa"
  },
  {
    "kontrola_ziadosti_vys_id": 60,
    "kontrola_ziadosti_id": 11,
    "typ_kontroly_ziadosti_id": 6,
    "hodnota": null,
    "vysledok": true,
    "typ_kontroly_ziadosti_label": "Nahrádzanie vyslaných zamestnancov",
    "zamestnavatelia": [
    ]
  }
]
